### PR TITLE
Added .' 2>&1' to the exec command.

### PR DESCRIPTION
**Pull request by ArtisanTinkerer**
https://stackoverflow.com/questions/3099617/php-capturing-the-command-output

This allows the errors to be retrieved into the $output array.

### CODE REVIEW

**Comment by cossou** [comment]
Hi @ArtisanTinkerer thanks for the PR.

I added some checks to the code. We had a similar feature but it was not working.

Do you spot any problem with that?

**Comment by ArtisanTinkerer** [comment]
No worries.

This is a great package, I was really stuck for a PHP reporting solution,
until I found this.

You just need to make sure that this line is correct;

exec($this->the_command .' 2>&1' , $output, $return_var);


It needs the 2>&1 so that the errors can be read.

Mick

**Comment by cossou** [comment]
Hi @ArtisanTinkerer it's in the previous lines (L164).

**Comment by ArtisanTinkerer** [comment]
Thanks, I see that now but it doesn't seem to work.

If I take off the > /dev/null it works.

Mick

**Comment by cossou** [comment]
The `/dev/null` was the problem. I removed in a commit to your own repository.

Take a look at the commits tab.

regards

**Comment by ArtisanTinkerer** [comment]
Looking good now.

**Pull request merged**
