### PR TITLE
 Upgraded to JasperStarter 3.2

### PR DESCRIPTION
**Pull request by StarkLiew**
Upgraded to JasperStarter 3.2 
Support JSON

### CODE REVIEW

**Comment by StarkLiew** [comment]
Upgrade to JasperStarter 3.2
Support JSON

**Comment by cossou** [comment]
Hi @StarkLiew 

thanks for the PR.
Could you provide a JSON example in the README?

**Comment by StarkLiew** [comment]
Hi @cossou 

Sure. I will update after I complete struggling to setup my VPS.

It pretty amazing using JSON file as the report is produced quit fast. But, will need hack trick to get the JSON object child data from data_report_source in designer. That will be pretty use to share data to sub report, list or table.
screen

**Comment by cossou** [comment]
Thanks! The invoice looks great! 👍

**Comment by StarkLiew** [comment]
Hi @cossou,
I have provide a JSON example in the README. Please take a look.

**Comment by cossou** [comment]
Thanks @StarkLiew merged!

**Pull request merged**
